(defrule r1 (monkey empty-hands) => (printout t"monkey is going to the box" crlf) (assert(monkey besides-box)))
(assert(monkey empty-hands))
(run)
(defrule r2 (monkey empty-hands)(monkey besides-box) => (printout t "monkey will take the box" crlf) (retract 1)(assert(monkey box-in-hands)))
(run)
(facts)
(defrule r3 (monkey box-in-hands)(monkey besides-box) => (printout t "monkey is going to take the banana" crlf) (retract 2)(assert(monkey below-banana)))
(run)
(facts)
(defrule r4 (monkey box-in-hands)(monkey below-banana) => (printout t "monkey will take the banana" crlf) (retract 3)(assert(monkey banana-in-hands)))
(run)
(facts)